// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVeJ3qU4_8NYqGepGKcK4c6svsUyl0ar8',
    appId: '1:688163969963:web:7713d30c7dc4b17ca710ee',
    messagingSenderId: '688163969963',
    projectId: 'feeds-1b714',
    authDomain: 'feeds-1b714.firebaseapp.com',
    storageBucket: 'feeds-1b714.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANNwU77mg61D69mnSN-CZ0fZib5kfR3Tc',
    appId: '1:688163969963:android:664cac6c494a24a1a710ee',
    messagingSenderId: '688163969963',
    projectId: 'feeds-1b714',
    storageBucket: 'feeds-1b714.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgXTZwHeJn8dWlRyPctUrQQHAY9xBgJgg',
    appId: '1:688163969963:ios:493852594b3442b7a710ee',
    messagingSenderId: '688163969963',
    projectId: 'feeds-1b714',
    storageBucket: 'feeds-1b714.firebasestorage.app',
    iosBundleId: 'com.example.appFeeds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgXTZwHeJn8dWlRyPctUrQQHAY9xBgJgg',
    appId: '1:688163969963:ios:493852594b3442b7a710ee',
    messagingSenderId: '688163969963',
    projectId: 'feeds-1b714',
    storageBucket: 'feeds-1b714.firebasestorage.app',
    iosBundleId: 'com.example.appFeeds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVeJ3qU4_8NYqGepGKcK4c6svsUyl0ar8',
    appId: '1:688163969963:web:24b3d612cfca4411a710ee',
    messagingSenderId: '688163969963',
    projectId: 'feeds-1b714',
    authDomain: 'feeds-1b714.firebaseapp.com',
    storageBucket: 'feeds-1b714.firebasestorage.app',
  );
}
