// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT_8ODA79toCSrIhOWfsEQ6E1DvaPonIQ',
    appId: '1:190318927922:web:0577a061c003704ff21c2b',
    messagingSenderId: '190318927922',
    projectId: 'feedcards-87a0a',
    authDomain: 'feedcards-87a0a.firebaseapp.com',
    storageBucket: 'feedcards-87a0a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs_DLUaZSGuvJUpJOr3LvsfCBUpjFGIqI',
    appId: '1:190318927922:android:7200d54c74a3a30bf21c2b',
    messagingSenderId: '190318927922',
    projectId: 'feedcards-87a0a',
    storageBucket: 'feedcards-87a0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzh-Z0EFvqXLiRT7N1TfPZrOq9PcMbatU',
    appId: '1:190318927922:ios:e2ea52159dd06249f21c2b',
    messagingSenderId: '190318927922',
    projectId: 'feedcards-87a0a',
    storageBucket: 'feedcards-87a0a.firebasestorage.app',
    iosClientId: '190318927922-ka1dq6903elrpu72tju0v4e93nj95vnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzh-Z0EFvqXLiRT7N1TfPZrOq9PcMbatU',
    appId: '1:190318927922:ios:e2ea52159dd06249f21c2b',
    messagingSenderId: '190318927922',
    projectId: 'feedcards-87a0a',
    storageBucket: 'feedcards-87a0a.firebasestorage.app',
    iosClientId: '190318927922-ka1dq6903elrpu72tju0v4e93nj95vnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT_8ODA79toCSrIhOWfsEQ6E1DvaPonIQ',
    appId: '1:190318927922:web:a97a322def3f469bf21c2b',
    messagingSenderId: '190318927922',
    projectId: 'feedcards-87a0a',
    authDomain: 'feedcards-87a0a.firebaseapp.com',
    storageBucket: 'feedcards-87a0a.firebasestorage.app',
  );

}